package com.genie.ws.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import com.genie.ws.service.impl.CxfDemoService;

import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-07-24T22:28:56.530+08:00
 * Generated source version: 3.2.5
 *
 */
@WebServiceClient(name = "demoService",
                  wsdlLocation = "http://127.0.0.1:8080/GenieProject/cxf/demo?wsdl",
                  targetNamespace = "http://127.0.0.1:8080")
public class DemoService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://127.0.0.1:8080", "demoService");
    public final static QName DemoPort = new QName("http://127.0.0.1:8080", "demoPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8080/GenieProject/cxf/demo?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DemoService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8080/GenieProject/cxf/demo?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DemoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DemoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DemoService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public DemoService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DemoService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DemoService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CxfDemoService
     */
    @WebEndpoint(name = "demoPort")
    public CxfDemoService getDemoPort() {
        return super.getPort(DemoPort, CxfDemoService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CxfDemoService
     */
    @WebEndpoint(name = "demoPort")
    public CxfDemoService getDemoPort(WebServiceFeature... features) {
        return super.getPort(DemoPort, CxfDemoService.class, features);
    }

}
