package com.genie.ws.service.impl;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-07-24T22:28:56.491+08:00
 * Generated source version: 3.2.5
 *
 */
@WebService(targetNamespace = "http://service.genie.com/", name = "CxfDemoService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface CxfDemoService {

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://service.genie.com/", partName = "return")
    public CxfEntityArray findAll();
}
