package com.genie.model;
// Generated 2017-4-11 22:06:28 by Hibernate Tools 4.3.1.Final

/**
 * TLogin generated by hbm2java
 */
public class LoginVO implements java.io.Serializable {

	private String username;
	private String password;

	public LoginVO() {
	}

	public LoginVO(String username, String password) {
		this.username = username;
		this.password = password;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
