// default package
// Generated 2017-11-8 22:22:22 by Hibernate Tools 4.3.1.Final

/**
 * TArea generated by hbm2java
 */
public class TArea implements java.io.Serializable {

	private TAreaId id;

	public TArea() {
	}

	public TArea(TAreaId id) {
		this.id = id;
	}

	public TAreaId getId() {
		return this.id;
	}

	public void setId(TAreaId id) {
		this.id = id;
	}

}
