// default package
// Generated 2017-11-8 22:22:22 by Hibernate Tools 4.3.1.Final

/**
 * TAreaId generated by hbm2java
 */
public class TAreaId implements java.io.Serializable {

	private Integer id;
	private String areaName;
	private Integer parentId;

	public TAreaId() {
	}

	public TAreaId(Integer id, String areaName, Integer parentId) {
		this.id = id;
		this.areaName = areaName;
		this.parentId = parentId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getAreaName() {
		return this.areaName;
	}

	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TAreaId))
			return false;
		TAreaId castOther = (TAreaId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getAreaName() == castOther.getAreaName()) || (this.getAreaName() != null
						&& castOther.getAreaName() != null && this.getAreaName().equals(castOther.getAreaName())))
				&& ((this.getParentId() == castOther.getParentId()) || (this.getParentId() != null
						&& castOther.getParentId() != null && this.getParentId().equals(castOther.getParentId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getAreaName() == null ? 0 : this.getAreaName().hashCode());
		result = 37 * result + (getParentId() == null ? 0 : this.getParentId().hashCode());
		return result;
	}

}
