package com.genie.entity;
// default package
// Generated 2017-10-17 22:07:29 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TChild generated by hbm2java
 */
public class Child implements java.io.Serializable {

	private Integer id;
	private String personId;
	private String childName;
	private Date birthday;
	private String sex;
	private String specialty;

	public Child() {
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	public String getPersonId() {
		return personId;
	}

	public void setPersonId(String persionId) {
		this.personId = persionId;
	}

	public String getChildName() {
		return this.childName;
	}

	public void setChildName(String childName) {
		this.childName = childName;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getSpecialty() {
		return this.specialty;
	}

	public void setSpecialty(String specialty) {
		this.specialty = specialty;
	}

	

}
