package com.genie.entity;
// Generated 2017-4-11 22:06:28 by Hibernate Tools 4.3.1.Final

/**
 * TLogin generated by hbm2java
 */
public class Login implements java.io.Serializable {

	private Integer id;
	private String username;
	private String password;

	public Login() {
	}

	public Login(String username, String password) {
		this.username = username;
		this.password = password;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
