package com.genie.entity;
// default package
// Generated 2017-11-8 22:22:22 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TOrgan generated by hbm2java
 */
public class Organ implements java.io.Serializable {

	private Integer id;
	private String organName;
	private Integer parentOrganId;
	private Integer contactId;
	private Set childs = new HashSet<Child>();

	public Organ() {
	}

	public Organ(String organName, Integer parentOrganId, Integer contactId) {
		this.organName = organName;
		this.parentOrganId = parentOrganId;
		this.contactId = contactId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getOrganName() {
		return this.organName;
	}

	public void setOrganName(String organName) {
		this.organName = organName;
	}

	public Integer getParentOrganId() {
		return this.parentOrganId;
	}

	public void setParentOrganId(Integer parentOrganId) {
		this.parentOrganId = parentOrganId;
	}

	public Integer getContactId() {
		return this.contactId;
	}

	public void setContactId(Integer contactId) {
		this.contactId = contactId;
	}

	public Set getChilds() {
		return childs;
	}

	public void setChilds(Set childs) {
		this.childs = childs;
	}

	
	
}
