package com.genie.entity;
// default package
// Generated 2017-10-17 22:07:29 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TParent generated by hbm2java
 */
public class Parent implements java.io.Serializable {

	private Integer id;
	private String personId;
	private String parentName;
	private String sex;
	private Integer contactId;
	private Set Childs = new HashSet(0);

	public Parent() {
	}

	public Parent(String parentName, String sex, Integer contactId, Set TChilds) {
		this.parentName = parentName;
		this.sex = sex;
		this.contactId = contactId;
		this.Childs = TChilds;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	
	
	public String getParentName() {
		return this.parentName;
	}

	public void setParentName(String parentName) {
		this.parentName = parentName;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Integer getContactId() {
		return this.contactId;
	}

	public void setContactId(Integer contactId) {
		this.contactId = contactId;
	}

	public Set getChilds() {
		return this.Childs;
	}

	public void setChilds(Set Childs) {
		this.Childs = Childs;
	}

	public String getPersonId() {
		return personId;
	}

	public void setPersonId(String personId) {
		this.personId = personId;
	}

}
