package com.genie.entity;
// default package
// Generated 2017-10-13 22:35:14 by Hibernate Tools 4.3.1.Final

/**
 * TUserinfo generated by hbm2java
 */
public class UserInfo implements java.io.Serializable {

	private Integer id;
	private String realName;
	private String personId;
	private String phone;
	private String sex;
	private Integer loginId;

	public UserInfo() {
	}

	public UserInfo(String realName, String personId, String phone, String sex, Integer loginId) {
		this.realName = realName;
		this.personId = personId;
		this.phone = phone;
		this.sex = sex;
		this.loginId = loginId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getRealName() {
		return this.realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

	public String getPersonId() {
		return this.personId;
	}

	public void setPersonId(String personId) {
		this.personId = personId;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Integer getLoginId() {
		return this.loginId;
	}

	public void setLoginId(Integer loginId) {
		this.loginId = loginId;
	}

}
